### ISSUE TITLE
Firefox plugin is stuck on loading animation

### ISSUE THREAD

**Issue by BingoRox** [Importantus/ArtfulTab#15]
Hasn't been working for a few days, the console shows a whole bunch of different errors and I tried reinstalling but no luck. Also thanks for your nice reply to my review on the add-on store!

**Comment by Importantus** [comment]
Aaaaah, I see it too. Will take a closer look, thanks for the report. :)

**Comment by Importantus** [comment]
Hey, the bug should be fixed. I've already uploaded the updated version to Chrome and Firefox, but it can take up to 24 hours (or longer if they do a manual check) for it to be released.

Edit (5 minutes later): They were fast, you can update to the new version for firefox now :)

**Comment by BingoRox** [comment]
Just tested, working great again! Thank you!!! Now you made my day! :)
