### ISSUE TITLE
Failed to load image error

### ISSUE THREAD

**Issue by BingoRox** [Importantus/ArtfulTab#17]
Hey, nice new error screen! Issues just started today, on Firefox again. 

Found this in the console: 
"SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

![image](https://github.com/user-attachments/assets/c4833374-35c2-45ed-9201-348b02ebefaf)

**Comment by Importantus** [comment]
Yes, there were some changes in an external tool I used (again). This time I removed the tool, so hopefully the fix is a bit more permanent ^^. I already pushed an update - can you check if you are on version 0.0.6?

**Comment by BingoRox** [comment]
Just updated to 0.0.6 and working great again! Fingers crossed!
